/* 
  Autogenerated:
    https://feathericons.com/?query=x
    https://react-svgr.com/playground/?typescript=true
*/

import * as React from "react"
import { SVGProps } from "react"

const SvgComponent = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    className="feather feather-x"
    {...props}
  >
    <path d="M18 6 6 18M6 6l12 12" />
  </svg>
)

export default SvgComponent
